name: CI/CD pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ${{ secrets.DEPLOY_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      APP_DIR: /home/ubuntu/test/cmd
      SERVICE_NAME: myapp.service  

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./...

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_KEY }}
          envs: APP_DIR,SERVICE_NAME
          script: |
            set -e
            echo "Deploying to $APP_DIR"
            cd $APP_DIR

            # Create backup
            TIMESTAMP=$(date +"%Y%m%d%H%M%S")
            echo "Creating backup directory: backup_$TIMESTAMP"
            cp -r current backup_$TIMESTAMP

            # Pull latest code
            echo "Pulling latest code..."
            if [ -d current ]; then
              cd current
              git pull origin master || {
                echo "Git pull failed. Rolling back..."
                cd ..
                rm -rf current
                cp -r backup_$TIMESTAMP current
                echo "Rollback completed from backup_$TIMESTAMP"
                exit 1
              }
            else
              git clone https://github.com/shuhaib-1/test.git current
            fi

            # Restart the service
            echo "Restarting service: $SERVICE_NAME"
            sudo systemctl restart $SERVICE_NAME
            echo "Deployment completed successfully"
      
      - name: Cleanup SSH Key 
        run: rm -f ~/.ssh/id_rsa