name: CI/CD Pipeline for user-api

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Setup SSH Key
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > s.pem
          chmod 400 s.pem

      - name: Pull Latest Code from Git
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            cd /home/ubuntu/test
            git pull origin master
          EOF

      - name: Testing and Building Go Application
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            # Update system packages
            sudo apt update
            sudo apt install -y golang-go
            
            # Verify Go installation
            go version

            # Navigate to the project directory and build the app
            cd /home/ubuntu/test
            go mod tidy
            go test ./... -v
            go build -o user-api ./cmd/main.go
          EOF

      - name: Restart Application Service
        env:
          EC2_USER: ${{ secrets.DEPLOY_USER }}
          EC2_IP: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i s.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            sudo systemctl restart thefurnishstore.service
          EOF

      - name: Cleanup
        run: |
          rm -f s.pem